version: 2.1

orbs:
  aws-parameter-store: circleci/aws-parameter-store@1.0.0

workflows:
  main:
    jobs:
      - aws-parameter-store/with-secrets:
          post-steps:
            - run: |
                env
                docker login -u $ktwl_username -p $ktwl_password
          context: temp_aws
