version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  docker_auth:
    docker:
      - image: cimg/python:3.9.7
    steps:
      - aws-cli/setup
      - run:
          name: set parameter from AWS parameter store
          command: |
            DOCKER_USERNAME=$(aws ssm get-parameter --with-decryption --name "ktwl_username" | jq '.Parameter.Value')
            echo "export DOCKER_USERNAME=${DOCKER_USERNAME}" >> $BASH_ENV
      - run:
          name: echo
          command: echo $DOCKER_USERNAME

workflows:
  main:
    jobs:
      - docker_auth
